name: Generate Javadocs
on:
  release

env:
  CMAKE_VERSION: "3.10.2.4988404"

jobs:
  build-and-deploy-javadocs:
    ## Only run on a release branch
    if: github.event_name == 'push' && contains(github.ref, 'refs/heads/release')
    name: Build and deploy Javadocs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Generate Aggregate Javadocs
        run: |
          ./gradlew aggregateJavadocs

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs/javadoc
          CLEAN: true
